[package]
name = "lib-calculator"
version = "0.1.0"
edition = "2021"

[dependencies]
lib-proc_macros = { path = "../lib-proc_macros" }
serde = "1.0.217"
cubecl = { version = "0.4.0", features = [
    "wgpu",
    "reduce",
] }
thiserror = "2.0.11"
ndarray = "0.16.1"